import type { PlacedPanel } from "./types";
import {
  CUT_COLOR,
  ENGRAVE_COLOR,
  CUT_STROKE_WIDTH,
  SLOT_WIDTH,
  SLOT_HEIGHT,
  HOLE_DIAMETER,
  SVG_MARGIN,
} from "./constants";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Escape &, <, >, " for safe XML text content. */
export function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Renders a rounded rect representing a slot mounting hole.
 * rx = ry = min(w, h) / 2
 */
export function svgSlot(cx: number, cy: number, w: number, h: number): string {
  const rx = Math.min(w, h) / 2;
  const x = cx - w / 2;
  const y = cy - h / 2;
  return (
    `<rect x="${x}" y="${y}" width="${w}" height="${h}" ` +
    `rx="${rx}" ry="${rx}" ` +
    `stroke="${CUT_COLOR}" stroke-width="${CUT_STROKE_WIDTH}" fill="none"/>`
  );
}

/** Renders a circle representing a round mounting hole. */
export function svgCircle(cx: number, cy: number, r: number): string {
  return (
    `<circle cx="${cx}" cy="${cy}" r="${r}" ` +
    `stroke="${CUT_COLOR}" stroke-width="${CUT_STROKE_WIDTH}" fill="none"/>`
  );
}

// ---------------------------------------------------------------------------
// Panel renderer
// ---------------------------------------------------------------------------

/** Render a single placed panel to SVG elements (without outer positioning). */
export function renderPanel(pp: PlacedPanel): string {
  const { spec, x, y, label } = pp;
  const { width, height, holes, holeStyle } = spec;

  // Font size: capped at 4mm, scales with panel dimensions
  const fontSize = Math.min(4, width * 0.08, height * 0.08);

  // Panel outline
  const outline =
    `<rect x="0" y="0" width="${width}" height="${height}" ` +
    `rx="0.5" ry="0.5" ` +
    `stroke="${CUT_COLOR}" stroke-width="${CUT_STROKE_WIDTH}" fill="none"/>`;

  // Centred engrave label
  const labelEl =
    `<text x="${width / 2}" y="${height / 2}" ` +
    `text-anchor="middle" dominant-baseline="central" ` +
    `font-family="monospace" font-size="${fontSize}" ` +
    `stroke="${ENGRAVE_COLOR}" stroke-width="0.05" fill="none">${escapeXml(label)}</text>`;

  // Mounting holes
  const holeElements = holes
    .map(([hx, hy]) => {
      if (holeStyle === "circle") {
        return svgCircle(hx, hy, HOLE_DIAMETER / 2);
      }
      return svgSlot(hx, hy, SLOT_WIDTH, SLOT_HEIGHT);
    })
    .join("\n    ");

  return (
    `<!-- Panel: ${escapeXml(label)} ${width}x${height}mm -->\n` +
    `<g transform="translate(${x}, ${y})">\n` +
    `  ${outline}\n` +
    `  ${labelEl}\n` +
    `  ${holeElements}\n` +
    `</g>`
  );
}

// ---------------------------------------------------------------------------
// Top-level SVG generator
// ---------------------------------------------------------------------------

/**
 * Generate a complete SVG document string for the given placed panels.
 *
 * @param placed  - Array of placed panels to render.
 * @param sheetW  - Sheet width in mm (excluding margin).
 * @param sheetH  - Sheet height in mm (excluding margin).
 * @param margin  - Outer margin added on all sides (default: SVG_MARGIN).
 */
export function generateSvg(
  placed: PlacedPanel[],
  sheetW: number,
  sheetH: number,
  margin: number = SVG_MARGIN
): string {
  const totalW = sheetW + 2 * margin;
  const totalH = sheetH + 2 * margin;

  const panelContent =
    placed.length > 0
      ? placed.map((pp) => `    ${renderPanel(pp).split("\n").join("\n    ")}`).join("\n")
      : "    <!-- no panels -->";

  return (
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<!-- Generated by rackcut -->\n` +
    `<!-- Cut color: ${CUT_COLOR} | Engrave color: ${ENGRAVE_COLOR} -->\n` +
    `<!-- Sheet: ${sheetW}x${sheetH}mm | Panels: ${placed.length} -->\n` +
    `<svg xmlns="http://www.w3.org/2000/svg"\n` +
    `     width="${totalW}mm" height="${totalH}mm"\n` +
    `     viewBox="0 0 ${totalW} ${totalH}">\n` +
    `  <g transform="translate(${margin}, ${margin})">\n` +
    `${panelContent}\n` +
    `  </g>\n` +
    `</svg>`
  );
}

// ---------------------------------------------------------------------------
// Download helper (browser only)
// ---------------------------------------------------------------------------

/**
 * Trigger a browser download of the given SVG string.
 *
 * @param svgString - Complete SVG document as a string.
 * @param filename  - Suggested filename for the download.
 */
export function downloadSvg(svgString: string, filename: string = "rackcut.svg"): void {
  const blob = new Blob([svgString], { type: "image/svg+xml" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}
